### ISSUE TITLE
error with plaint-text output

### ISSUE THREAD

**Issue by MathuraMG** [MathuraMG/p5-interceptor#7]
reported by @garryson361 - [Issue](https://github.com/processing/p5.js-web-editor/issues/461#issuecomment-339485072)

When I run the code below (on my account), I get the error:
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'. (sketch: line 45)
I have tried not being on my account and when I log off, the error doesn't happen
code:
var x = 600
var speed = 1
function setup() {
createCanvas(400, 400);
}

function draw() {
var time = Math.round(x / 0.6) / 100
var fuse = x / 10
background(220);
rect(x,10,1,1)
text(time,10,10)
fill(255,10,10)
for(var i = 0;i < 5; i++){
rect(180,180,10,100)
}
for(var j = 0; j < fuse ;j++){
rect(184,178 - j / 1,2,2)
}
x = x - speed
}
there is probably a simple fix but I can't find it

@lm-n @cleezyITP

**Comment by MathuraMG** [comment]
hi @garryson361 - to summarize, the issue is with the plain-text output that is used along with a screen reader to make the output more accessible. 
Are you using a screen reader along with the p5 IDE, and if so, please could you let us know which browser and screen reader so that we can document that.

Thank you!

**Comment by garryson361** [comment]
I am not using a screen reader.
But I am on Google Chrome.

**Comment by CleezyITP** [comment]
Hi @garryson361, the feature is only usable with a screen reader. It serves as a non-visual, text-based output for users of assistive technology. Here is some info on the project: [http://ability.nyu.edu/processing](http://ability.nyu.edu/processing)

**Comment by lm-n** [comment]
@MathuraMG fix#7 looks good and works when I run @garryson361 's code!
